CREATE TABLE facilities (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key VARCHAR2(64 CHAR) NOT NULL,
  source_dataset VARCHAR2(80 CHAR) NOT NULL,
  name VARCHAR2(200 CHAR) NOT NULL,
  facility_type VARCHAR2(100 CHAR) NOT NULL,
  address VARCHAR2(300 CHAR) NOT NULL,
  detail_location VARCHAR2(500 CHAR),
  latitude NUMBER(10, 7) NOT NULL,
  longitude NUMBER(10, 7) NOT NULL,
  location MDSYS.SDO_GEOMETRY NOT NULL,
  opening_hours VARCHAR2(200 CHAR),
  status VARCHAR2(20 CHAR) DEFAULT 'available' NOT NULL,
  status_text VARCHAR2(100 CHAR),
  verified NUMBER(1) DEFAULT 0 NOT NULL,
  manager_name VARCHAR2(200 CHAR),
  manager_phone VARCHAR2(50 CHAR),
  source_name VARCHAR2(200 CHAR),
  source_url VARCHAR2(500 CHAR),
  source_updated_at TIMESTAMP WITH TIME ZONE,
  note VARCHAR2(1000 CHAR),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT facilities_status_ck CHECK (status IN ('available', 'busy', 'unavailable')),
  CONSTRAINT facilities_verified_ck CHECK (verified IN (0, 1)),
  CONSTRAINT facilities_latitude_ck CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT facilities_longitude_ck CHECK (longitude BETWEEN -180 AND 180),
  CONSTRAINT facilities_source_key_uk UNIQUE (source_key)
);

CREATE TABLE facility_categories (
  facility_id NUMBER NOT NULL,
  category_id VARCHAR2(20 CHAR) NOT NULL,
  CONSTRAINT facility_categories_pk PRIMARY KEY (facility_id, category_id),
  CONSTRAINT facility_categories_facility_fk FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE,
  CONSTRAINT facility_categories_id_ck CHECK (category_id IN ('general', 'recycle', 'medicine', 'battery', 'clothes', 'cigarette'))
);

CREATE TABLE facility_accepted_items (
  facility_id NUMBER NOT NULL,
  item_name VARCHAR2(120 CHAR) NOT NULL,
  sort_order NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT facility_accepted_items_pk PRIMARY KEY (facility_id, item_name),
  CONSTRAINT facility_accepted_items_facility_fk FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE
);

CREATE TABLE waste_items (
  id VARCHAR2(80 CHAR) PRIMARY KEY,
  name VARCHAR2(120 CHAR) NOT NULL,
  category_id VARCHAR2(20 CHAR) NOT NULL,
  disposal_tip VARCHAR2(1000 CHAR) NOT NULL,
  active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT waste_items_category_ck CHECK (category_id IN ('general', 'recycle', 'medicine', 'battery', 'clothes', 'cigarette')),
  CONSTRAINT waste_items_active_ck CHECK (active IN (0, 1))
);

CREATE TABLE waste_item_aliases (
  waste_item_id VARCHAR2(80 CHAR) NOT NULL,
  alias VARCHAR2(120 CHAR) NOT NULL,
  CONSTRAINT waste_item_aliases_pk PRIMARY KEY (waste_item_id, alias),
  CONSTRAINT waste_item_aliases_item_fk FOREIGN KEY (waste_item_id) REFERENCES waste_items(id) ON DELETE CASCADE
);

CREATE TABLE users (
  id VARCHAR2(36 CHAR) PRIMARY KEY,
  email VARCHAR2(254 CHAR) NOT NULL,
  display_name VARCHAR2(30 CHAR) NOT NULL,
  password_hash VARCHAR2(300 CHAR) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT users_email_uk UNIQUE (email)
);

CREATE TABLE auth_sessions (
  token_hash VARCHAR2(64 CHAR) PRIMARY KEY,
  user_id VARCHAR2(36 CHAR) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT auth_sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_reports (
  id VARCHAR2(36 CHAR) PRIMARY KEY,
  facility_id NUMBER NOT NULL,
  user_id VARCHAR2(36 CHAR) NOT NULL,
  report_type VARCHAR2(20 CHAR) NOT NULL,
  content VARCHAR2(1000 CHAR) NOT NULL,
  status VARCHAR2(20 CHAR) DEFAULT 'received' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT user_reports_facility_fk FOREIGN KEY (facility_id) REFERENCES facilities(id),
  CONSTRAINT user_reports_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT user_reports_type_ck CHECK (report_type IN ('full', 'missing', 'broken', 'location', 'info')),
  CONSTRAINT user_reports_status_ck CHECK (status IN ('received', 'reviewing', 'resolved'))
);

INSERT INTO user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
VALUES (
  'FACILITIES',
  'LOCATION',
  MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.005),
    MDSYS.SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.005)
  ),
  4326
);

CREATE INDEX facilities_location_sidx ON facilities(location) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;
CREATE INDEX facilities_lat_lng_idx ON facilities(latitude, longitude);
CREATE INDEX facilities_updated_idx ON facilities(updated_at);
CREATE INDEX facilities_dataset_idx ON facilities(source_dataset, source_key);
CREATE INDEX facility_categories_category_idx ON facility_categories(category_id, facility_id);
CREATE INDEX auth_sessions_user_idx ON auth_sessions(user_id, expires_at);
CREATE INDEX user_reports_user_idx ON user_reports(user_id, created_at);

CREATE OR REPLACE TRIGGER facilities_location_trigger
BEFORE INSERT OR UPDATE ON facilities
FOR EACH ROW
BEGIN
  IF INSERTING OR UPDATING('LATITUDE') OR UPDATING('LONGITUDE') THEN
    :NEW.location := MDSYS.SDO_GEOMETRY(
      2001,
      4326,
      MDSYS.SDO_POINT_TYPE(:NEW.longitude, :NEW.latitude, NULL),
      NULL,
      NULL
    );
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER user_reports_updated_trigger
BEFORE UPDATE ON user_reports
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
